#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Курс data analyst/Python/Pandas/Data/supermarket_sales.csv")
type(df)

pandas.core.frame.DataFrame

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [ ]:
df.groupby('Branch')['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [ ]:
df.groupby(['Branch', 'City'])[['gross income', 'Total']].sum()

                  gross income        Total
Branch City
A      Yangon        5057.1605  106200.3705
B      Mandalay      5057.0320  106197.6720
C      Naypyitaw     5265.1765  110568.7065

У місті Naypyitaw

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [ ]:
invoices_by_category = pd.pivot_table(df, index = 'Branch', columns= 'Product line', values = 'Invoice ID', aggfunc = 'count')

In [ ]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [ ]:
invoices_by_category.sort_values(by = ['Electronic accessories', 'Branch'], ascending= False).head(1)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59

Branch A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Customer type по Branch
2. Покупки по категоріях по місяцях
3. Вподобання по категоріях в залежності від статі покупця

In [ ]:
cust_type_by_branch = pd.pivot_table(df, index = 'Branch', columns= 'Customer type', values = 'Total', aggfunc= ('sum', 'count'))

In [ ]:
cust_type_by_branch

               count                sum
Customer type Member Normal      Member     Normal
Branch
A                167    173  53637.4755  52562.895
B                165    167  53704.6860  52492.986
C                169    159  56881.2825  53687.424

In [ ]:
df["Month"] = pd.to_datetime(df["Date"]).dt.month

In [ ]:
category_by_month = pd.pivot_table (df, index = 'Month', columns= 'Product line', values = 'Total', aggfunc='sum')

In [ ]:
category_by_month

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Month,,,,,,
1,18831.2880,19345.1160,19570.530,16383.1710,20494.7400,21667.0230
2,17362.9050,19009.8615,20000.358,14602.2555,12434.3835,13809.6105
3,18143.3385,15950.9175,16573.956,18208.3125,20932.7895,19646.1930

In [ ]:
category_by_sex = pd.pivot_table(
    df,
    index="Product line",
    columns="Gender",
    values="Total",
    aggfunc="sum",
)

In [ ]:
category_by_sex

Gender                      Female        Male
Product line
Electronic accessories  27102.0225  27235.5090
Fashion accessories     30437.4000  23868.4950
Food and beverages      33170.9175  22973.9265
Health and beauty       18560.9865  30632.7525
Home and lifestyle      30036.8775  23825.0355
Sports and travel       28574.7210  26548.1055

У всіх філіях кількість покупців зі статусом Member та суми їхніх покупок є вищими прівняно зі звичайними покупцями.
Спрямувати додаткові маркетингові зусилля на залучення клієнтів у систему лояльності (наприклад, давати бонуси за реєстрацію в додатку чи на касі), оскільки Member генерують стабільний і вищий дохід.


Найменший обсяг продажів серед чоловіків зафіксовано в категоріях Food and beverages та Home and lifestyle.
Щоб залучити чоловіків до купівлі продуктів харчування та товарів для дому, можна використовувати крос-продажі — наприклад, розміщувати готові снеки, енергетичні напої чи каву поруч із відділом електроніки та спортивних товарів, які вони купують найчастіше.